=== RENCI-NRIG/nodeagent2/orca-external/node-agent2/trunk/agent/config/src/main/resources/orca/nodeagent2/agent/config/xsd/AgentConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://geni-orca.renci.org/xml/node-agent2/AgentConfig" xmlns:tns="http://geni-orca.renci.org/xml/node-agent2/AgentConfig" elementFormDefault="qualified">


    <complexType name="propertyType">
    	<attribute name="name" type="string"></attribute>
    	<attribute name="value" type="string"></attribute>
    </complexType>

    <complexType name="propertiesType">
    	<sequence>
    		<element name="property" type="tns:propertyType" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="pluginType">
    	<all>
    		<element name="jar" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="mainClass" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="schedulePeriod" type="tns:timeUnit"
    			minOccurs="1" maxOccurs="1">
    		</element>
    		<element name="renewAdvanceTicks" type="int"
    		    minOccurs="0" maxOccurs="1">
    		</element>
    		<element name="config" type="string" minOccurs="0"
    			maxOccurs="1">
    		</element>
    		<element name="properties" type="tns:propertiesType"
    			minOccurs="0" maxOccurs="1">
    		</element>
    		<element name="description" type="string" minOccurs="0"
    			maxOccurs="1">
    		</element>
    	</all>
    	<attribute name="name" type="tns:pluginNamePattern"></attribute>
    </complexType>

    <complexType name="pluginsType">
    	<sequence>
    		<element name="plugin" type="tns:pluginType" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="agentConfigType">
    	<all>
    	   	<element name="tick" type="tns:timeUnit" 
    			minOccurs="1" maxOccurs="1">
    		</element>
    		<element name="plugins" type="tns:pluginsType" maxOccurs="1"
    			minOccurs="1">
    		</element>
    	</all>
    	<attribute name="password" type="string"></attribute>
    </complexType>

    <element name="agentConfig" type="tns:agentConfigType"></element>

	<simpleType name="unitChoice">
	  <restriction base="string">
	    <enumeration value="week"/>
	    <enumeration value="day"/>
	    <enumeration value="hour"/>
	    <enumeration value="minute"/>
	    <enumeration value="second"/>
	  </restriction>
	</simpleType>
	
	<simpleType name="pluginNamePattern">
		<restriction base="string">
			<pattern value="[a-zA-Z0-9-]+"/>
			<minLength value="5"/>
      		<maxLength value="20"/>
		</restriction>
	</simpleType>

	<complexType name="timeUnit">
		<attribute name="length" type="int"></attribute>
		<attribute name="unit" type="tns:unitChoice"></attribute>
	</complexType>
</schema>

=== RENCI-NRIG/nodeagent2/agent/config/src/main/resources/orca/nodeagent2/agent/config/xsd/test-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<agentConfig xmlns="http://geni-orca.renci.org/xml/node-agent2/AgentConfig"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://geni-orca.renci.org/xml/node-agent2/AgentConfig http://geni-orca.renci.org/xml/node-agent2/AgentConfig.xsd"
	password="pass">

	<plugins>
		<plugin name="Null Plugin">
			<jar>/some/file/name.jar</jar>
			<mainClass>some.class.name</mainClass>
			<schedulePeriod length="0"><minute/></schedulePeriod>
			<config>/etc/orca/am+broker/node-config</config>
			<endpoint>null</endpoint>
			<properties>
				<property name="pr" value="val" />
				<property name="pr1" value="val1" />
			</properties>
		</plugin>
		<plugin name="Null1 Plugin">
			<jar>/other/file/name.jar</jar>
			<mainClass>other.class.name</mainClass>
			<schedulePeriod length="1"><week/></schedulePeriod>
			<config>/etc/orca/am+broker/node-config</config>
			<endpoint>null1</endpoint>
			<properties>
				<property name="pr" value="val" />
				<property name="pr1" value="val1" />
			</properties>
		</plugin>
	</plugins>

</agentConfig>

=== RENCI-NRIG/nodeagent2/redhat/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<agentConfig xmlns="http://geni-orca.renci.org/xml/node-agent2/AgentConfig"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://geni-orca.renci.org/xml/node-agent2/AgentConfig http://geni-orca.renci.org/xml/node-agent2/AgentConfig.xsd"
	password="pass">

	<tick length="1" unit="minute"/>
	<plugins>
		<plugin name="null-plugin">
			<jar>/opt/nodeagent2/plugins/na2-null-plugin.jar</jar>
			<mainClass>org.renci.nodeagent2.null_agent.Main</mainClass>
			<schedulePeriod length="3" unit="minute" />
			<renewAdvanceTicks>2</renewAdvanceTicks>
			<description>Null plugin for testing</description>
			<properties>
				<property name="pr" value="val" />
				<property name="pr1" value="val1" />
			</properties>
		</plugin>
		<!--
		<plugin name="oscars">
			<jar>/opt/nodeagent2/plugins/na2-oscars-plugin.jar</jar>
			<mainClass>org.renci.nodeagent2.oscarslib.Main</mainClass>
			<schedulePeriod length="6" unit="minute" />
			<renewAdvanceTicks>2</renewAdvanceTicks>
			<properties>
				<property name="oscars.keystore" value="/some/path/to/jks" />
				<property name="oscars.truststore" value="/some/path/to/jks" />
				<property name="oscars.alias" value="some-alias" />
				<property name="oscars.password" value="some-password" />
				<property name="oscars.description" value="ORCA-NA2-circuit" />
			</properties>
		</plugin>
		-->
                <!--
		<plugin name="execplug" >
			<jar>/opt/nodeagent2/plugins/na2-exec-plugin.jar</jar>
			<mainClass>org.renci.nodeagent2.exec.Main</mainClass>
			<schedulePeriod length="3" unit="minute" />
			<properties>
				<property name="exec.join" value="/some/path/to/join.sh" />
				<property name="exec.leave" value="/some/path/to/leave.sh" />
				<property name="exec.modify" value="/some/path/to/modify.sh" />
				<property name="exec.renew" value="/some/path/to/renew.sh" />
				<property name="exec.status" value="/some/path/to/status.sh" />
			</properties>
		</plugin>
		-->
	</plugins>
</agentConfig>

=== RENCI-NRIG/nodeagent2/orca-external/node-agent2/trunk/agent/server/na-test-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<agentConfig xmlns="http://geni-orca.renci.org/xml/node-agent2/AgentConfig"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://geni-orca.renci.org/xml/node-agent2/AgentConfig http://geni-orca.renci.org/xml/node-agent2/AgentConfig.xsd"
	password="pass">

	<tick length="1" unit="minute"/>
	<plugins>
		<plugin name="null-plugin">
			<jar>/Users/ibaldin/workspace-nodeagent2/node-agent2/null-agent/target/null-agent-0.1-SNAPSHOT-jar-with-dependencies.jar</jar>
			<mainClass>orca.nodeagent2.null_agent.Main</mainClass>
			<schedulePeriod length="3" unit="minute" />
			<renewAdvanceTicks>2</renewAdvanceTicks>
			<description>Null plugin for testing</description>
			<properties>
				<property name="pr" value="val" />
				<property name="pr1" value="val1" />
			</properties>
		</plugin>
		<plugin name="oscars">
			<!--
			<jar>/Users/ibaldin/workspace-oscars/na2-oscars-lib/target/na2-oscars-lib-0.6SNAPSHOT.jar</jar>
			-->
	
			<jar>/Users/ibaldin/workspace-oscars/na2-oscars-v06/target/oscars-0.6-SNAPSHOT-jar-with-dependencies.jar</jar>
			<mainClass>orca.nodeagent2.oscarsv06.Main</mainClass>
			<schedulePeriod length="5" unit="minute" />
			<properties>
				<property name="oscars.keystore" value="/Users/ibaldin/workspace-oscars/orca-oscars-0.6/scripts/oscars-orca3.jks" />
				<property name="oscars.truststore" value="/Users/ibaldin/workspace-oscars/orca-oscars-0.6/scripts/oscars-orca3.jks" />
				<property name="oscars.alias" value="orca" />
				<property name="oscars.password" value="VeryTough55!" />
				<property name="oscars.description" value="ORCA-NA2-circuit" />
			</properties>
		</plugin>
	</plugins>
</agentConfig>

=== RENCI-NRIG/nodeagent2/agent/server/na-test-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<agentConfig xmlns="http://geni-orca.renci.org/xml/node-agent2/AgentConfig"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://geni-orca.renci.org/xml/node-agent2/AgentConfig http://geni-orca.renci.org/xml/node-agent2/AgentConfig.xsd"
	password="pass">

	<tick length="10" unit="second"/>
	<plugins>
		<plugin name="Null-Test-Plugin">
			<jar>/Users/ibaldin/workspace-nodeagent2/node-agent2/null-agent/target/null-agent-0.1-SNAPSHOT-jar-with-dependencies.jar</jar>
			<mainClass>orca.nodeagent2.null_agent.Main</mainClass>
			<schedulePeriod length="3" unit="minute" />
			<renewAdvanceTicks>2</renewAdvanceTicks>
			<description>Null plugin for testing</description>
			<properties>
				<property name="pr" value="val" />
				<property name="pr1" value="val1" />
			</properties>
		</plugin>
		<plugin name="Some-Test-Plugin">
			<jar>/Users/ibaldin/workspace-nodeagent2/node-agent2/null-agent/target/null-agent-0.1-SNAPSHOT.jar</jar>
			<mainClass>orca.nodeagent2.null_agent.Main</mainClass>
			<schedulePeriod length="60" unit="second" />
			<properties>
				<property name="pr" value="val" />
				<property name="pr1" value="val1" />
			</properties>
		</plugin>
	</plugins>
</agentConfig>
